#!/bin/bash

#faust2api -android -nvoices 16 -effect synth_effect.dsp -nodoc synth.dsp
faust2api -android -nvoices 16 -effect synth_effect.dsp -nodoc new/midiOnly.dsp
#faust2api -android -nvoices 1 -nodoc new/toy.dsp

unzip dsp-faust.zip
cp dsp-faust/cpp/* ../android/Faust/app/src/main/cpp
cp dsp-faust/java/* ../android/Faust/app/src/main/java/com/DspFaust
rm -r dsp-faust
rm dsp-faust.zip
