#!/bin/bash

faust2api -android -polyvoices 16 -effect synth_effect.dsp -nodoc synth.dsp

unzip dsp-faust.zip
cp dsp-faust/cpp/* ../android/Faust/app/src/main/cpp
cp dsp-faust/java/* ../android/Faust/app/src/main/java/com/DspFaust
rm -r dsp-faust
rm dsp-faust.zip
