#!/bin/bash

faust2api -ios -nvoices 16 -midi -effect synth_effect.dsp -nodoc new/drums.dsp
#faust2api -ios -polyvoices 12 -midi -nodoc noPoly.dsp
#faust2api -ios -polyvoices 12 -midi -nodoc midiOnly.dsp
unzip dsp-faust.zip
cp dsp-faust/DspFaust.cpp ../iOS/Faust/Faust
cp dsp-faust/DspFaust.h ../iOS/Faust/Faust
rm -r dsp-faust
rm dsp-faust.zip